# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0002_assignment_assignmentresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentResponseManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
