# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0002_announcements_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
