# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiler', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Interest')),
                ('student', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Student')),
            ],
        ),
        migrations.AddField(
            model_name='facultyinterest',
            name='interest',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Interest'),
        ),
    ]
